name: Branch Protection Rules

protect-main:
  pattern: main
  enforce_admins: true
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  restrictions:
    users: []
    teams: []
    apps: []
  required_status_checks:
    strict: true
    contexts: []
  allow_force_pushes: false
  allow_deletions: false