name: Branch Protection

on:
  push:
    branches:
      - main

jobs:
  protect-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Direct pushes to main branch are not allowed. Please create a pull request instead."
            exit 1
          fi